# -*- coding: utf-8 -*-
"""ODP_vs_H264_PER-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrfYKB5KkC52gBtUfKLSCirHfDeK2mHH

# One-D-Piece vs H.264 under Packet Loss — Real-Time Semantic Video

**Goal.** Compare One-D-Piece (ODP) token communication against H.264 for transmitting video over a lossy channel, measuring **question answering (VLM)** and **image quality (SSIM)** as a function of packet error rate (PER) from 5% to 35%.

**What 'H.264 (ffmpeg)' means.** H.264/AVC is the video-compression *standard* used by YouTube, Zoom, Blu-ray. `ffmpeg` with `libx264` is the real encoder that implements it. We feed the actual video frames to libx264, get a genuine H.264 bitstream with real I-frames (self-contained keyframes) and P-frames (predicted from the previous frame), and decode it back. `ffprobe` gives us each frame's real byte size and type. So this is not a model of H.264 — it is H.264.

**The flow.**
```
video -> [encode] -> packetize bits into packets -> Bernoulli packet drop (PER)
      -> [decode what arrived] -> reconstructed frame -> SSIM + VLM question answering
```
- **ODP**: 256 ordered tokens, split into packets. Lost tail packets => shorter valid prefix => coarser but coherent image (never garbage).
- **H.264**: frame split into MPDUs; a lost MPDU corrupts the entropy stream => frame lost (freeze). A lost I-frame freezes the whole GOP (cascade).

**Real-time.** Everything must run at 25 fps = 40 ms/frame. The decoder is the bottleneck, so we benchmark decode latency (mean + p95) and compare **ODP regular vs ODP FP16+torch.compile**, including the quality loss the acceleration costs.

This notebook is fully self-contained — no external files to upload.

## 0 — Install
"""

import os, subprocess

# Python packages
os.system('pip install -q timm einops omegaconf huggingface_hub accelerate '
          'open_clip_torch imageio[ffmpeg] av safetensors')
print('packages: ok')

# Clone bytedance/1d-tokenizer — TiTok base architecture (always needed)
if not os.path.exists('1d-tokenizer'):
    os.system('git clone -q https://github.com/bytedance/1d-tokenizer.git')
ok = os.path.exists('1d-tokenizer/modeling/titok.py')
print(f'1d-tokenizer repo: {"ok" if ok else "MISSING"}')
if not ok:
    raise RuntimeError('1d-tokenizer clone failed')

# Clone One-D-Piece (ICML 2025, Turing Motors) — TTD-trained weights
# GitHub: turingmotors/One-D-Piece   HF: turing-motors/One-D-Piece-B-256
if not os.path.exists('One-D-Piece'):
    print('Cloning One-D-Piece...')
    ret = os.system(
        'git clone --depth 1 '
        'https://github.com/turingmotors/One-D-Piece.git')
    if ret == 0 and os.path.exists('One-D-Piece'):
        # List the eval configs so we know exact filenames
        import glob
        cfgs = glob.glob('One-D-Piece/configs/one-d-piece*.yaml')
        print(f'One-D-Piece repo: ok  ({len(cfgs)} eval configs found)')
        for c in sorted(cfgs): print(f'  {c}')
    else:
        print('One-D-Piece repo: clone failed — One-D-Piece weights unavailable')
        print('  TiTok (64 tokens) will be used as fallback — demo still works')
else:
    import glob
    cfgs = glob.glob('One-D-Piece/configs/one-d-piece*.yaml')
    print(f'One-D-Piece repo: already present  ({len(cfgs)} eval configs)')

"""## 1 — Device, metrics, CLIP, BLIP-VQA"""

import torch, numpy as np
from PIL import Image
DEVICE='cuda' if torch.cuda.is_available() else 'cpu'
IMG_SIZE=256; FPS=25; FRAME_MS=1000/FPS
print('device:',DEVICE,'| frame budget:',FRAME_MS,'ms')

def ssim(a,b):
    a=np.asarray(a,float); b=np.asarray(b,float)
    mu_a,mu_b=a.mean(),b.mean(); va,vb=a.var(),b.var(); cov=((a-mu_a)*(b-mu_b)).mean()
    c1,c2=(0.01*255)**2,(0.03*255)**2
    return float(((2*mu_a*mu_b+c1)*(2*cov+c2))/((mu_a**2+mu_b**2+c1)*(va+vb+c2)))
def psnr(a,b):
    a=np.asarray(a,float); b=np.asarray(b,float); mse=np.mean((a-b)**2)
    return float(20*np.log10(255/np.sqrt(mse))) if mse>0 else 99.0

from transformers import CLIPModel, CLIPProcessor
_clip=CLIPModel.from_pretrained('openai/clip-vit-base-patch32').to(DEVICE).eval()
_cp=CLIPProcessor.from_pretrained('openai/clip-vit-base-patch32')
def clip_sim(a,b):
    with torch.no_grad():
        ia=_cp(images=Image.fromarray(np.asarray(a).astype('uint8')),return_tensors='pt').to(DEVICE)
        ib=_cp(images=Image.fromarray(np.asarray(b).astype('uint8')),return_tensors='pt').to(DEVICE)
        fa=_clip.get_image_features(**ia); fb=_clip.get_image_features(**ib)
        if not torch.is_tensor(fa): fa=fa.image_embeds if hasattr(fa,'image_embeds') else fa.pooler_output
        if not torch.is_tensor(fb): fb=fb.image_embeds if hasattr(fb,'image_embeds') else fb.pooler_output
        fa=fa/fa.norm(dim=-1,keepdim=True); fb=fb/fb.norm(dim=-1,keepdim=True)
        return float((fa*fb).sum())

from transformers import BlipProcessor, BlipForQuestionAnswering
_vp=BlipProcessor.from_pretrained('Salesforce/blip-vqa-base')
_vqa=BlipForQuestionAnswering.from_pretrained('Salesforce/blip-vqa-base').to(DEVICE).eval()
def ask_vlm(img,q):
    try:
        inp=_vp(Image.fromarray(np.asarray(img).astype('uint8')),q,return_tensors='pt').to(DEVICE)
        with torch.no_grad(): out=_vqa.generate(**inp,max_length=20)
        return _vp.decode(out[0],skip_special_tokens=True).strip().lower()
    except Exception as e: return f'[error {e}]'

QUESTIONS=['What is the main subject or animal in this image?',
           'What is the subject doing or how is it moving?',
           'What colors are most prominent in the scene?',
           'What is in the background?',
           'What type of environment or setting is this?']

def text_match(a,b):
    if not a or not b or '[error' in a or '[error' in b: return 0.0
    a=a.strip().lower().rstrip('.').strip(); b=b.strip().lower().rstrip('.').strip()
    if a==b: return 1.0
    if a in b.split() or b in a.split(): return 1.0
    SYN=[{'moving','walking','running','grazing','eating','standing'},
         {'rural','countryside','farm','field','pasture','outdoor','outdoors','nature'},
         {'trees','forest','woods','foliage','vegetation'},{'green','greenery'},
         {'sky','clouds'},{'mountains','mountain','hills'},{'horse','horses','pony'}]
    for g in SYN:
        if a in g and b in g: return 1.0
    if (set(a.split())&set(b.split()))-{'a','an','the','is','are','of','in','on'}: return 0.5
    return 0.0

def vlm_acc(orig,recon):
    if recon is None: return 0.0
    sc=[]
    for q in QUESTIONS:
        oa=ask_vlm(orig,q); ra=ask_vlm(recon,q)
        if oa and '[error' not in oa: sc.append(text_match(oa,ra))
    return float(np.mean(sc)) if sc else 0.0
print('metrics + VLM ready')

"""## 2 — Load One-D-Piece (regular) and build the FP16+compile variant

Both variants use the **same weights** — only the decode precision/compilation differs. So any quality difference between them is purely the cost of acceleration, which we measure explicitly.
"""

import sys, warnings
warnings.filterwarnings('ignore')

# Prefer One-D-Piece (has TTD + same TiTok architecture), fall back to 1d-tokenizer
REPO = 'One-D-Piece' if os.path.exists('One-D-Piece/modeling/titok.py') else '1d-tokenizer'
USING_ODP = REPO == 'One-D-Piece'
print(f'Using repo  : {REPO}')
print(f'One-D-Piece : {USING_ODP}')
if REPO not in sys.path:
    sys.path.insert(0, REPO)

from modeling.titok import TiTok   # correct import path
print(f'TiTok imported: OK  (from {REPO}/modeling/titok.py)')

import torch
from omegaconf import OmegaConf
from huggingface_hub import hf_hub_download

DEVICE = 'cuda'
model = None; N_TOKENS = None; CODEBOOK_SIZE = None; MODEL_ID = None


def _test_model(m):
    """Verify model works with a dummy forward pass and return (N_TOKENS, codebook_size)."""
    m = m.to(DEVICE).eval()
    with torch.no_grad():
        zq, rd = m.encode(torch.zeros(1, 3, 256, 256, device=DEVICE))
    n  = zq.shape[-1]                          # num_latent_tokens
    cb = m.quantize.embedding.num_embeddings   # codebook size
    return m, n, cb


# One-D-Piece HF repos contain ONLY pytorch_model.bin (no config).
# Config is fetched directly from GitHub raw URL — no local clone needed.
import urllib.request as _ur
_RAW = 'https://raw.githubusercontent.com/turingmotors/One-D-Piece/main'
ODP_CONFIGS = {
    'turing-motors/One-D-Piece-B-256': f'{_RAW}/configs/one-d-piece_b256.yaml',
    'turing-motors/One-D-Piece-L-256': f'{_RAW}/configs/one-d-piece_l256.yaml',
    'turing-motors/One-D-Piece-S-256': f'{_RAW}/configs/one-d-piece_s256.yaml',
}

def _fetch_config_yaml(url, dest):
    """Download a config YAML from GitHub raw URL."""
    req = _ur.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with _ur.urlopen(req, timeout=15) as r, open(dest, 'wb') as f:
        f.write(r.read())

def try_from_pretrained(hf_id):
    """Load model: from_pretrained → One-D-Piece bin+raw-config → config.yaml → fail."""
    global model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID
    print(f'  {hf_id} ...', end=' ')

    # Path A: from_pretrained with config.json (yucornetto TiTok models)
    try:
        m, n, cb = _test_model(TiTok.from_pretrained(hf_id))
        model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID = m, n, cb, hf_id
        print(f'OK  N={n}  Q={cb}')
        return True
    except Exception:
        pass

    # Path B: One-D-Piece — fetch config from GitHub raw URL + bin from HF
    raw_url = ODP_CONFIGS.get(hf_id)
    if raw_url:
        try:
            cfg_path = f'/tmp/odp_config_{hf_id.split("/")[-1]}.yaml'
            # Try local clone first, then GitHub raw URL
            size_key = hf_id.split('-')[3].lower()  # B, L, or S
            local_cfg = f'One-D-Piece/configs/one-d-piece_{size_key}256.yaml'
            if os.path.exists(local_cfg):
                import shutil; shutil.copy(local_cfg, cfg_path)
            else:
                _fetch_config_yaml(raw_url, cfg_path)
            ckpt = hf_hub_download(hf_id, 'pytorch_model.bin')
            cfg  = OmegaConf.load(cfg_path)
            m    = TiTok(cfg)
            sd   = torch.load(ckpt, map_location='cpu', weights_only=False)
            if isinstance(sd, dict) and 'state_dict' in sd: sd = sd['state_dict']
            if isinstance(sd, dict) and 'model' in sd:      sd = sd['model']
            m.load_state_dict(sd, strict=False)
            m, n, cb = _test_model(m)
            model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID = m, n, cb, hf_id
            print(f'OK  N={n}  Q={cb}  (bin+github-config)')
            return True
        except Exception as e2:
            print(f'failed: {e2}')
            return False

    # Path C: manual config.yaml in HF repo (other repos)
    try:
        cfg_path  = hf_hub_download(hf_id, 'config.yaml')
        ckpt_path = hf_hub_download(hf_id, 'pytorch_model.bin')
        cfg = OmegaConf.load(cfg_path)
        m   = TiTok(cfg)
        sd  = torch.load(ckpt_path, map_location='cpu', weights_only=False)
        m.load_state_dict(sd, strict=False)
        m, n, cb = _test_model(m)
        model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID = m, n, cb, hf_id
        print(f'OK  N={n}  Q={cb}  (config.yaml)')
        return True
    except Exception:
        pass

    # Path D: build One-D-Piece config programmatically (no file needed)
    # Architecture parameters derived from paper + TiTok codebase.
    if 'One-D-Piece' in hf_id:
        try:
            # Map HF model name → architecture size
            _arch = {'B': 'vit_b_672', 'L': 'vit_l_1024', 'S': 'vit_s_512'}
            _size = 'B' if '-B-' in hf_id else ('L' if '-L-' in hf_id else 'S')
            _vit  = _arch.get(_size, 'vit_b_672')
            cfg = OmegaConf.create({
                'model': {
                    'vq_model': {
                        'codebook_size': 4096,
                        'token_size': 12,
                        'use_l2_norm': True,
                        'commitment_cost': 0.25,
                        'vit_enc_model_size': _vit,
                        'vit_dec_model_size': _vit,
                        'num_latent_tokens': 256,
                        'image_size': 256,
                        'finetune_decoder': False,
                    }
                }
            })
            ckpt = hf_hub_download(hf_id, 'pytorch_model.bin')
            m    = TiTok(cfg)
            sd   = torch.load(ckpt, map_location='cpu', weights_only=False)
            if isinstance(sd, dict) and 'state_dict' in sd: sd = sd['state_dict']
            if isinstance(sd, dict) and 'model' in sd:      sd = sd['model']
            m.load_state_dict(sd, strict=False)
            m, n, cb = _test_model(m)
            model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID = m, n, cb, hf_id
            print(f'OK  N={n}  Q={cb}  (programmatic config)')
            return True
        except Exception as e4:
            print(f'failed: {e4}')
    return False


def try_bin_download(repo_id, filename, cfg_yaml):
    """Download .bin weights from fun-research/TiTok and load with local YAML config."""
    global model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID
    print(f'  fun-research/TiTok/{filename} ...', end=' ')
    try:
        ckpt = hf_hub_download(repo_id=repo_id, filename=filename, local_dir='/tmp/titok')
        cfg  = OmegaConf.load(cfg_yaml)
        m    = TiTok(cfg)
        sd   = torch.load(ckpt, map_location='cpu', weights_only=True)
        m.load_state_dict(sd, strict=False)
        m, n, cb = _test_model(m)
        model, N_TOKENS, CODEBOOK_SIZE, MODEL_ID = m, n, cb, filename.replace('.bin', '')
        print(f'OK  N={n}  Q={cb}')
        return True
    except Exception as e:
        print(f'failed: {e}')
        return False


print('Loading tokenizer model...')

# ── Option 1: One-D-Piece (TTD-trained, semantically ordered tokens) ─────────
# HF org is 'turing-motors' (with hyphen), model names are PascalCase
if model is None:
    for hf_id in [
        'turing-motors/One-D-Piece-B-256',   # base  — best balance of speed & quality
        'turing-motors/One-D-Piece-L-256',   # large — highest quality
        'turing-motors/One-D-Piece-S-256',   # small — fastest
    ]:
        if try_from_pretrained(hf_id):
            break

# ── Option 2: TiTok base (no TTD, but same decoder — still works) ────────────
if model is None:
    for hf_id in [
        'yucornetto/tokenizer_titok_b64_imagenet',
        'yucornetto/tokenizer_titok_l32_imagenet',
        'yucornetto/tokenizer_titok_s128_imagenet',
    ]:
        if try_from_pretrained(hf_id):
            break

# ── Option 2: .bin from fun-research/TiTok (reliable public fallback) ─────────
if model is None:
    CFG = '1d-tokenizer/configs/infer/TiTok'
    for fname, yaml in [
        ('tokenizer_titok_b64.bin', f'{CFG}/titok_b64.yaml'),
        ('tokenizer_titok_l32.bin', f'{CFG}/titok_l32.yaml'),
        ('tokenizer_titok_s128.bin', f'{CFG}/titok_s128.yaml'),
    ]:
        if try_bin_download('fun-research/TiTok', fname, yaml):
            break

if model is None:
    raise RuntimeError(
        'All model candidates failed.\n'
        'Check Colab has internet access and HuggingFace is reachable.\n'
        'Manual fallback: upload tokenizer_titok_b64.bin from '
        'https://huggingface.co/fun-research/TiTok and re-run.'
    )

BITS_PER_TOKEN = max(1, (CODEBOOK_SIZE - 1).bit_length())
print(f'\nReady: {MODEL_ID}  |  N={N_TOKENS} tokens  |  Q={CODEBOOK_SIZE}  |  {BITS_PER_TOKEN} bits/token')

# ── Image quality expectation ─────────────────────────────────────────────
IS_ONE_D_PIECE = 'one-d-piece' in MODEL_ID.lower() or 'turing-motors' in MODEL_ID.lower()
if IS_ONE_D_PIECE:
    print('\n  Model: One-D-Piece (TTD-trained)')
    print('  Expected: paper-quality images at k=8 — decoder has learned generative prior')
    print('  At k=8/256: blurry but clearly recognisable (global structure from head tokens)')
else:
    print(f'\n  Model: {MODEL_ID} (base TiTok, NOT TTD-trained)')
    print(f'  N={N_TOKENS} tokens.  TiTok was trained with FIXED token count — no variable-length.')
    print(f'  At low k: images WILL look bad.  This is expected for base TiTok.')
    print(f'  For paper-quality at low k: load turing-motors/One-D-Piece-B-256')
    print(f'  The TCLA QoE advantage vs H.265 freeze is still demonstrated correctly.')

import numpy as np
from PIL import Image
import torch, warnings
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
warnings.filterwarnings('ignore')

IMG_SIZE = 256


def _to_tensor(pil_img):
    """PIL image -> (1,3,256,256) float32 in [0,1].  TiTok expects [0,1], not [-1,1]."""
    arr = np.array(pil_img.convert('RGB').resize((IMG_SIZE, IMG_SIZE))).astype(np.float32)
    return torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0).div(255.0).to(DEVICE)


def _to_uint8(tensor):
    """(1,3,H,W) float32 [0,1] -> (H,W,3) uint8."""
    arr = torch.clamp(tensor, 0.0, 1.0).squeeze(0).permute(1, 2, 0).cpu().float().numpy()
    return (arr * 255.0).astype(np.uint8)


# Mean codebook embedding — used as neutral fill for masked tail positions
with torch.no_grad():
    _MEAN_EMB = model.quantize.embedding.weight.mean(dim=0).to(DEVICE)  # shape (token_size,)
print(f'Mean codebook embedding: {_MEAN_EMB.shape}  device={_MEAN_EMB.device}')


def tokenize(pil_img):
    """
    Encode a PIL image.
    Returns:
        zq  : (1, C, 1, N)  float32  — continuous quantized latents (for decode path)
        ids : (N,)           int64   — discrete token indices (what is transmitted)
    The ids are what TCLA actually transmits — k integer IDs per frame.
    """
    x = _to_tensor(pil_img)
    with torch.no_grad():
        zq, rd = model.encode(x)
    ids = rd['min_encoding_indices'].reshape(-1).cpu().numpy().astype(np.int64)
    return zq, ids


# ── Determine decode strategy based on loaded model ─────────────────────────
# One-D-Piece (TTD-trained): supports variable-length via decode_tokens(ids[:k])
#   → decoder receives k tokens as keys/values, hallucinates the rest from priors
#   → produces paper-quality images at k=8 (see Figure 1)
# Base TiTok (no TTD): fixed-length decoder; variable-length not trained
#   → mean-fill fallback, poor quality at low k (expected behaviour)

_DECODE_STRATEGY = None   # set on first decode_prefix call

def _probe_decode_strategy():
    """Test which decode path works for the loaded model."""
    global _DECODE_STRATEGY
    try:
        # Test 1: decode_tokens with short integer sequence (preferred — matches protocol)
        dummy_ids = torch.zeros(1, max(1, N_TOKENS//4), dtype=torch.long, device=DEVICE)
        with torch.no_grad():
            out = model.decode_tokens(dummy_ids)
        assert out.shape[-1] == IMG_SIZE
        _DECODE_STRATEGY = 'decode_tokens'
        print(f'  Decode strategy: decode_tokens() — variable-length OK')
        print(f'  This is One-D-Piece (TTD-trained): paper-quality at low k expected')
    except (AssertionError, RuntimeError, Exception) as e1:
        try:
            # Test 2: decode with truncated z tensor
            dummy_z = torch.zeros(1, model.quantize.embedding.weight.shape[1],
                                   1, N_TOKENS//4, device=DEVICE)
            with torch.no_grad():
                out = model.decode(dummy_z)
            _DECODE_STRATEGY = 'decode_z'
            print(f'  Decode strategy: model.decode(z[:k]) — variable-length OK via z')
        except Exception as e2:
            _DECODE_STRATEGY = 'mean_fill'
            print(f'  Decode strategy: mean-fill fallback (base TiTok, fixed-length decoder)')
            print(f'  Quality at low k will be poor — load turing-motors/One-D-Piece-B-256')
            print(f'  for paper-quality reconstruction at 8–32 tokens')

    return _DECODE_STRATEGY


def decode_prefix(zq, k, token_ids=None):
    """
    Reconstruct image from first k tokens.

    Uses the best available decode strategy in priority order:

    1. decode_tokens(ids[:k])  — correct protocol path: transmit k integer IDs,
       receiver calls decode_tokens. If One-D-Piece, this gives TTD-quality images.

    2. model.decode(z[:,:,:,:k]) — pass k continuous embeddings, same result.

    3. mean-fill fallback — base TiTok only. Quality at low k is poor because
       TiTok was never trained with variable-length inputs (no TTD).

    For paper-quality images at k=8–32, you must load One-D-Piece (TTD-trained).
    """
    global _DECODE_STRATEGY
    if _DECODE_STRATEGY is None:
        _probe_decode_strategy()

    k = max(1, min(k, N_TOKENS))

    if _DECODE_STRATEGY == 'decode_tokens' and token_ids is not None:
        # decode_tokens expects (B, 1, k) — it does squeeze(1) internally
        # Using (1, k) fails when k=1 because squeeze(1) gives a 1D tensor
        ids_t = torch.from_numpy(
            token_ids[:k].astype(np.int64)
        ).reshape(1, 1, k).to(DEVICE)           # (1, 1, k)
        with torch.no_grad():
            recon = model.decode_tokens(ids_t)   # (1, 3, H, W)
        return _to_uint8(recon)

    if _DECODE_STRATEGY in ('decode_tokens', 'decode_z'):
        # ── Second path: continuous quantized embeddings
        try:
            z_prefix = zq[:, :, :, :k]
            with torch.no_grad():
                recon = model.decode(z_prefix)
            return _to_uint8(recon)
        except (AssertionError, RuntimeError):
            _DECODE_STRATEGY = 'mean_fill'

    # ── Fallback: mean-fill (base TiTok, not TTD-trained)
    z = zq.clone()
    if k < N_TOKENS:
        z[:, :, 0, k:] = _MEAN_EMB.view(1,-1,1).expand(1,-1,N_TOKENS-k)
    with torch.no_grad():
        recon = model.decode(z)
    return _to_uint8(recon)

# ── FP16 + torch.compile decoder variant (same weights, faster) ─────────────
# Regular path = decode_prefix (defined above). Fast path wraps the same model.
N_TOKENS_C = N_TOKENS      # alias used downstream
BITS_PER_TOKEN_C = BITS_PER_TOKEN

_compiled_dec = None
def _build_compiled():
    global _compiled_dec
    def _f(ids_t):
        with torch.no_grad():
            return model.decode_tokens(ids_t)
    try:
        _compiled_dec = torch.compile(_f, mode='reduce-overhead')
    except Exception as e:
        print('torch.compile unavailable, using eager:', e)
        _compiled_dec = _f
_build_compiled()

def _unpack(tok):
    """Accept either (zq, ids) tuple or a bare zq."""
    if isinstance(tok, tuple): return tok[0], tok[1]
    return tok, None

def odp_decode_regular(tok, k, token_ids=None):
    """Regular FP32 decode of the first k tokens. `tok` may be (zq, ids)."""
    if k <= 0: return None
    zq, ids = _unpack(tok)
    return decode_prefix(zq, k, token_ids=token_ids if token_ids is not None else ids)

def odp_decode_fast(tok, k, token_ids=None):
    """FP16 + compiled decode of the first k tokens (same weights). `tok` may be (zq, ids)."""
    if k <= 0: return None
    zq, ids = _unpack(tok)
    if token_ids is None: token_ids = ids
    if _DECODE_STRATEGY is None: _probe_decode_strategy()
    k = max(1, min(k, N_TOKENS))
    if _DECODE_STRATEGY == 'decode_tokens' and token_ids is not None:
        ids_t = torch.from_numpy(token_ids[:k].astype(np.int64)).reshape(1,1,k).to(DEVICE)
        if DEVICE=='cuda':
            with torch.autocast(device_type='cuda', dtype=torch.float16):
                out = _compiled_dec(ids_t)
        else:
            out = _compiled_dec(ids_t)
        return _to_uint8(out.float())
    # fallback: regular path
    return decode_prefix(zq, k, token_ids=token_ids)

# odp_encode alias to the proven tokenize() (returns (zq, ids))
def odp_encode(img):
    zq, ids = tokenize(Image.fromarray(np.asarray(img).astype('uint8')))
    return zq, ids
print('regular + FP16/compile decoders ready (built on proven decode_prefix)')

"""## 3 — Decode latency (25fps check) + FP16+compile quality loss"""

import time
def _sync():
    if torch.cuda.is_available(): torch.cuda.synchronize()
def bench(fn,nw=5,nt=20):
    for _ in range(nw):
        try: fn()
        except Exception as e: return None
        _sync()
    ts=[]
    for _ in range(nt):
        t0=time.perf_counter(); fn(); _sync(); ts.append((time.perf_counter()-t0)*1000)
    a=np.array(ts); return dict(mean=a.mean(),p95=np.percentile(a,95),mn=a.min())

# need a sample frame; defined after video load, so guard
def decode_timing_report(sample_img):
    ids=odp_encode(sample_img)
    print(f'{"variant":<22}{"k":>5}{"mean ms":>10}{"p95 ms":>9}  25fps(40ms)')
    print('-'*56)
    DT={'regular':{}, 'fast':{}}
    for k in [32,64,128,256]:
        br=bench(lambda kk=k: odp_decode_regular(ids,kk))
        bf=bench(lambda kk=k: odp_decode_fast(ids,kk),nw=8)
        DT['regular'][k]=br; DT['fast'][k]=bf
        for label,b in [('regular',br),('FP16+compile',bf)]:
            if b: print(f'{label:<22}{k:>5}{b["mean"]:>10.1f}{b["p95"]:>9.1f}  '
                        f'{"OK" if b["p95"]<40 else "MISS"}')
        print()
    # quality loss of FP16+compile vs regular (clean, no packet loss)
    print('FP16+compile quality loss vs regular (same frame, k=256):')
    rg=odp_decode_regular(ids,256); ft=odp_decode_fast(ids,256)
    print(f'  SSIM(regular vs fast)={ssim(rg,ft):.4f}  PSNR={psnr(rg,ft):.1f}dB')
    print(f'  CLIP(regular vs fast)={clip_sim(rg,ft):.4f}')
    print(f'  VLM agreement={vlm_acc(rg,ft):.3f}  (1.0 = identical answers)')
    return DT
print('run decode_timing_report(frames[0]) after loading video')

"""## 4 — Load video frames"""

import subprocess, os
VIDEO_PATH='/content/video.mp4'   # <-- your uploaded mp4
N_FRAMES=60
if os.path.exists(VIDEO_PATH):
    raw=subprocess.run(['ffmpeg','-i',VIDEO_PATH,'-vf',f'scale={IMG_SIZE}:{IMG_SIZE},fps=25',
        '-frames:v',str(N_FRAMES),'-f','rawvideo','-pix_fmt','rgb24','pipe:1'],
        capture_output=True).stdout
    fb=IMG_SIZE*IMG_SIZE*3
    frames=[np.frombuffer(raw[i*fb:(i+1)*fb],np.uint8).reshape(IMG_SIZE,IMG_SIZE,3) for i in range(len(raw)//fb)]
    print(f'loaded {len(frames)} frames')
else:
    frames=[]; base=np.random.randint(40,200,(IMG_SIZE,IMG_SIZE,3),np.uint8)
    for i in range(N_FRAMES):
        f=base.copy(); x=(20+i*4)%200; f[100:150,x:x+40]=[110,75,45]; frames.append(f)
    print(f'no video at {VIDEO_PATH}; using {len(frames)} synthetic frames')

DT=decode_timing_report(frames[0])

"""## 5 — Encode: ODP tokens + real H.264 (ffmpeg/libx264)"""

import json as _json
GOP=12; H264_CRF=28

# ODP tokens per frame
odp_ids=[odp_encode(f) for f in frames]

# Real H.264 encode
_raw=b''.join(f.tobytes() for f in frames)
subprocess.run(['ffmpeg','-y','-f','rawvideo','-pix_fmt','rgb24','-s',f'{IMG_SIZE}x{IMG_SIZE}',
    '-r','25','-i','pipe:0','-c:v','libx264','-g',str(GOP),'-bf','0','-crf',str(H264_CRF),
    '-pix_fmt','yuv420p','/tmp/h264.mp4'],input=_raw,capture_output=True)
_pr=subprocess.run(['ffprobe','-select_streams','v','-show_frames','-show_entries',
    'frame=pict_type,pkt_size','-of','json','/tmp/h264.mp4'],capture_output=True,text=True)
_fr=_json.loads(_pr.stdout)['frames']
h264_type=[x.get('pict_type','P') for x in _fr][:len(frames)]
h264_bytes=[int(x.get('pkt_size',0)) for x in _fr][:len(frames)]
_dr=subprocess.run(['ffmpeg','-i','/tmp/h264.mp4','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],
    capture_output=True).stdout
fb=IMG_SIZE*IMG_SIZE*3
h264_dec=[np.frombuffer(_dr[i*fb:(i+1)*fb],np.uint8).reshape(IMG_SIZE,IMG_SIZE,3) for i in range(len(_dr)//fb)]

# real H.264 per-frame decode latency (constant-ish)
def _h264_decode_all():
    return subprocess.run(['ffmpeg','-i','/tmp/h264.mp4','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],capture_output=True).stdout
_t0=time.perf_counter(); _h264_decode_all(); H264_DEC_MS=(time.perf_counter()-_t0)*1000/len(frames)

nI=sum(1 for t in h264_type if t=='I')
print(f'ODP: {N_TOKENS} tokens x {BITS_PER_TOKEN}b = {N_TOKENS*BITS_PER_TOKEN//8} B/frame (constant)')
print(f'H.264: {nI} I-frames (~{np.mean([b for b,t in zip(h264_bytes,h264_type) if t=="I"])/1024:.0f}KB) '
      f'+ {len(frames)-nI} P-frames (~{np.mean([b for b,t in zip(h264_bytes,h264_type) if t=="P"]):.0f}B)')
print(f'H.264 decode ~{H264_DEC_MS:.2f} ms/frame')

"""## 6 — Packetization and Bernoulli drop model

Each frame's bits are split into packets; each packet is dropped i.i.d. with probability PER. **ODP** keeps the longest contiguous *prefix* of arrived token-packets. **H.264** loses the whole frame if any packet drops (entropy stream), and a lost I-frame cascades the GOP. No retransmission — a dropped packet is lost for that 40ms window.
"""

MPDU_BYTES=1500
PKT_TOKENS=32              # ODP: tokens per packet (256/32 = 8 packets/frame)
def n_mpdus(nbytes): return max(1,int(np.ceil(nbytes/MPDU_BYTES)))

def odp_prefix_after_loss(p,rng):
    npk=N_TOKENS//PKT_TOKENS
    recv=rng.random(npk)>=p
    if not recv[0]: return 0
    if recv.all(): return N_TOKENS
    return int(np.argmin(recv))*PKT_TOKENS   # contiguous prefix length

def h264_frame_ok(nbytes,p,rng):
    return bool((rng.random(n_mpdus(nbytes))>=p).all())

# latency lookup: ODP decode time depends on surviving k
def odp_latency_ms(k,variant):
    if k<=0: return FRAME_MS    # frozen: no decode, but a frame slot still elapses
    # nearest benchmarked k
    ks=sorted(DT[variant].keys()); kk=min(ks,key=lambda x:abs(x-k))
    return DT[variant][kk]['mean']
print(f'ODP packets/frame: {N_TOKENS//PKT_TOKENS} (each {PKT_TOKENS} tokens = {PKT_TOKENS*BITS_PER_TOKEN//8} B)')

"""## 7 — Simulation sweep: PER 5% to 35%"""

from dataclasses import dataclass
PER_LEVELS=[0.05,0.10,0.15,0.20,0.25,0.30,0.35]
VLM_EVERY=3
ODP_VARIANT='fast'   # 'regular' or 'fast' (FP16+compile) for the latency accounting

@dataclass
class R: codec:str; p:float; i:int; ssim:float; vlm:float; lat:float; frozen:bool; k:int

results=[]
for p in PER_LEVELS:
    print(f'PER {p*100:.0f}% ...', end=' ')
    rng=np.random.default_rng(int(p*1000)+7)
    odp_last=None; h_last=None; gop_alive=False
    for i,frm in enumerate(frames):
        do_vlm=(i%VLM_EVERY==0)
        # ODP
        k=odp_prefix_after_loss(p,rng)
        if k>0:
            rec=odp_decode_regular(odp_ids[i],k); odp_last=rec; fz=False
        else: rec=odp_last if odp_last is not None else frm; fz=True
        lat=odp_latency_ms(k,ODP_VARIANT)
        results.append(R('ODP',p,i,ssim(frm,rec),vlm_acc(frm,rec) if do_vlm else -1,lat,fz,k))
        # H.264
        is_I=(h264_type[i]=='I'); ok=h264_frame_ok(h264_bytes[i],p,rng)
        if is_I:
            if ok: h_last=h264_dec[i]; gop_alive=True; hfz=False
            else: h_last=h_last if h_last is not None else frm; gop_alive=False; hfz=True
        else:
            if gop_alive and ok: h_last=h264_dec[i]; hfz=False
            else: h_last=h_last if h_last is not None else frm; hfz=True
        hr=h_last if h_last is not None else frm
        results.append(R('H.264',p,i,ssim(frm,hr),vlm_acc(frm,hr) if do_vlm else -1,H264_DEC_MS,hfz,-1))
    print('done')
print(f'{len(results)} frame-results')

"""## 8 — Results: mean and p95 vs PER

For **latency** the meaningful tail is high (p95 = slow frames that threaten the 40ms budget). For **quality** the meaningful tail is low (p5 = worst frames), so we report mean with the [p5, p95] band.
"""

def agg(codec,p,attr,only_vlm=False):
    vs=[getattr(r,attr) for r in results if r.codec==codec and r.p==p and (not only_vlm or r.vlm>=0)]
    return np.array(vs)

print(f'{"Codec":<7}{"PER":>5}{"SSIM mean":>11}{"SSIM p5":>9}{"VLM mean":>10}{"VLM p5":>8}'
      f'{"Lat mean":>10}{"Lat p95":>9}{"Freeze%":>9}')
print('-'*78)
summary={}
for p in PER_LEVELS:
    for c in ['ODP','H.264']:
        s=agg(c,p,'ssim'); v=agg(c,p,'vlm',only_vlm=True); l=agg(c,p,'lat')
        fz=agg(c,p,'frozen').mean()*100
        d=dict(ssim_mean=s.mean(),ssim_p5=np.percentile(s,5),ssim_p95=np.percentile(s,95),
               vlm_mean=v.mean() if len(v) else 0,vlm_p5=np.percentile(v,5) if len(v) else 0,
               vlm_p95=np.percentile(v,95) if len(v) else 0,
               lat_mean=l.mean(),lat_p95=np.percentile(l,95),freeze=fz)
        summary[(c,p)]=d
        print(f'{c:<7}{p*100:>4.0f}%{d["ssim_mean"]:>11.3f}{d["ssim_p5"]:>9.3f}'
              f'{d["vlm_mean"]:>10.3f}{d["vlm_p5"]:>8.3f}{d["lat_mean"]:>9.1f}m{d["lat_p95"]:>8.1f}m{fz:>8.1f}%')
    print()

"""## 9 — Plots: VLM, SSIM, and latency vs PER (mean + bands)"""

import matplotlib.pyplot as plt
COL={'ODP':'#15803d','H.264':'#dc2626'}
x=[p*100 for p in PER_LEVELS]
fig,(a1,a2,a3)=plt.subplots(1,3,figsize=(17,4.8)); fig.patch.set_facecolor('white')
for c in ['ODP','H.264']:
    vm=[summary[(c,p)]['vlm_mean'] for p in PER_LEVELS]
    vlo=[summary[(c,p)]['vlm_p5'] for p in PER_LEVELS]; vhi=[summary[(c,p)]['vlm_p95'] for p in PER_LEVELS]
    a1.plot(x,vm,'o-',color=COL[c],lw=2.4,label=c); a1.fill_between(x,vlo,vhi,color=COL[c],alpha=0.12)
    sm=[summary[(c,p)]['ssim_mean'] for p in PER_LEVELS]
    slo=[summary[(c,p)]['ssim_p5'] for p in PER_LEVELS]; shi=[summary[(c,p)]['ssim_p95'] for p in PER_LEVELS]
    a2.plot(x,sm,'o-',color=COL[c],lw=2.4,label=c); a2.fill_between(x,slo,shi,color=COL[c],alpha=0.12)
    lm=[summary[(c,p)]['lat_mean'] for p in PER_LEVELS]; lp=[summary[(c,p)]['lat_p95'] for p in PER_LEVELS]
    a3.plot(x,lm,'o-',color=COL[c],lw=2.4,label=f'{c} mean'); a3.plot(x,lp,'^--',color=COL[c],lw=1.6,label=f'{c} p95')
a3.axhline(FRAME_MS,color='#333',ls=':',lw=1.5,label=f'{FRAME_MS:.0f}ms (25fps)')
a1.set_title('VLM accuracy vs PER'); a1.set_ylabel('VLM accuracy'); a1.set_ylim(0,1.05)
a2.set_title('SSIM vs PER'); a2.set_ylabel('SSIM'); a2.set_ylim(0,1.05)
a3.set_title('Decode latency vs PER'); a3.set_ylabel('ms')
for a in (a1,a2,a3):
    a.set_xlabel('PER (%)'); a.legend(fontsize=8); a.grid(alpha=0.15)
    a.spines['top'].set_visible(False); a.spines['right'].set_visible(False)
plt.tight_layout(); plt.savefig('/tmp/odp_vs_h264.png',dpi=140,bbox_inches='tight',facecolor='white'); plt.show()
print(f'ODP latency uses the {ODP_VARIANT} decoder. Shaded band = [p5,p95] across frames.')

"""## 10 — Reconstructed video: Original | ODP | H.264 at a chosen PER"""

import base64
from PIL import ImageDraw, ImageFont
from IPython.display import HTML, display
RENDER_P=0.10
try: F1=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',13); F2=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',10)
except: F1=F2=ImageFont.load_default()
W=IMG_SIZE; HUD=56; NP=3; OW=W*NP; OH=W+HUD
if OW%2:OW+=1
if OH%2:OH+=1
rng=np.random.default_rng(int(RENDER_P*1000)+7); odp_last=None; h_last=None; gop_alive=False
proc=subprocess.Popen(['ffmpeg','-y','-f','rawvideo','-pix_fmt','rgb24','-s',f'{OW}x{OH}','-r','25',
    '-i','pipe:0','-c:v','libx264','-pix_fmt','yuv420p','-crf','18','/tmp/recon.mp4'],
    stdin=subprocess.PIPE,stderr=subprocess.DEVNULL)
VLM_Q=QUESTIONS[0]; ans={'ODP':'','H.264':'','Original':''}
def pan(img,title,col,extra,answer,frozen):
    c=Image.new('RGB',(W,OH),(12,12,12)); c.paste(Image.fromarray(img.astype(np.uint8)),(0,0)); d=ImageDraw.Draw(c)
    if frozen:
        ov=Image.new('RGBA',(W,W),(180,40,40,70)); c.paste(Image.alpha_composite(c.crop((0,0,W,W)).convert('RGBA'),ov).convert('RGB'),(0,0)); d=ImageDraw.Draw(c)
        d.text((W//2,12),'FROZEN',font=F1,fill=(255,180,180),anchor='mt')
    d.rectangle([0,W,W,OH],fill=(18,18,18)); d.text((6,W+3),title,font=F1,fill=col)
    if extra: d.text((W-72,W+3),extra,font=F2,fill=(170,170,170))
    a=(answer[:30]+'…') if len(answer)>30 else answer
    d.text((6,W+22),f'A: {a}',font=F2,fill=(150,210,150))
    return np.array(c)
for i,frm in enumerate(frames):
    k=odp_prefix_after_loss(RENDER_P,rng)
    if k>0: orec=odp_decode_regular(odp_ids[i],k); odp_last=orec; ofz=False
    else: orec=odp_last if odp_last is not None else frm; ofz=True
    is_I=(h264_type[i]=='I'); ok=h264_frame_ok(h264_bytes[i],RENDER_P,rng)
    if is_I:
        if ok: h_last=h264_dec[i]; gop_alive=True; hfz=False
        else: h_last=h_last if h_last is not None else frm; gop_alive=False; hfz=True
    else:
        if gop_alive and ok: h_last=h264_dec[i]; hfz=False
        else: h_last=h_last if h_last is not None else frm; hfz=True
    hr=h_last if h_last is not None else frm
    if i%VLM_EVERY==0:
        ans['Original']=ask_vlm(frm,VLM_Q); ans['ODP']=ask_vlm(orec,VLM_Q); ans['H.264']=ask_vlm(hr,VLM_Q)
    row=np.concatenate([pan(frm,'Original',(255,255,255),'',ans['Original'],False),
                        pan(orec,'ODP',(105,240,150),f'k={k}',ans['ODP'],ofz),
                        pan(hr,'H.264',(255,120,100),h264_type[i],ans['H.264'],hfz)],axis=1)
    if row.shape[1]<OW: row=np.pad(row,((0,0),(0,OW-row.shape[1]),(0,0)))
    proc.stdin.write(row.tobytes())
proc.stdin.close(); proc.wait()
with open('/tmp/recon.mp4','rb') as f: b64=base64.b64encode(f.read()).decode()
display(HTML(f'<video width="{min(OW,1000)}" controls autoplay loop muted>'
  f'<source src="data:video/mp4;base64,{b64}" type="video/mp4"></video>'
  f'<p style="color:#888;font-size:12px">PER={RENDER_P*100:.0f}%  Original | ODP (k tokens) | H.264 (I/P)</p>'))

"""## 11 — Summary

- **H.264 (ffmpeg)** is a *real* H.264 encode via libx264 — real I/P frames, real sizes. Not a model.
- Under packet loss, ODP keeps a valid token *prefix* (coarser image, still answerable by the VLM); H.264 loses whole frames and cascades the GOP on a lost I-frame, so it freezes.
- **Latency / 25fps**: cell 3 shows whether each decoder fits 40ms. **FP16+compile** is the variant that makes ODP real-time; its quality loss vs regular ODP is reported there (SSIM/PSNR/CLIP/VLM on identical input — typically negligible since it's the same weights at lower precision).
- **Reading the plots**: VLM and SSIM use mean + [p5,p95] band (quality tail is the low end); latency uses mean + p95 (the slow tail that threatens the deadline).
"""