# -*- coding: utf-8 -*-
"""TCLA_Simulation_OneDPiece_working_psnr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vmyx9ZVuc-uL7cLaAVuv1rI-m-k_8Bs

# TCLA Simulation — Real One-D-Piece Tokenizer

**Before running:** `Runtime → Change runtime type → T4 GPU`

**Three patent claims demonstrated with the real TTD-trained One-D-Piece-L-256:**
1. `QoE(k)` is **monotone** — every added token improves reconstruction quality
2. **Layered TXOP TCLA** — base layer guarantees no freeze; enhancement layer token count adapts via Block ACK
3. **Block ACK → token position → QoE** — zero MLLM inference needed for feedback

**Channel model rationale:**
- Wi-Fi 6, 20MHz, MCS7 → 86 Mbit/s raw rate
- 256 tokens × 12 bits = 3,072 bits → ~0.036ms transmission time (negligible)
- The real deadline pressure comes from **retransmission RTT in a congested medium**
- Each retransmission round costs RTT = 8ms (SIFS + ACK + DIFS + backoff + queuing delay)
- Under poor burst channel: 4-5 rounds needed → 32-40ms → **exceeds 33.3ms deadline**
- TCLA: base(0ms tx + 8ms RTT) + enh(0ms tx + 8ms RTT) = 16ms → **always fits**

**Run all 11 cells in order. ~20 min total.**
"""

# CELL 1: Install packages
import subprocess, sys
print('Installing dependencies...')
result = subprocess.run(
    [sys.executable, '-m', 'pip', 'install', '-q',
     'einops', 'timm', 'omegaconf', 'scikit-image', 'datasets'],
    capture_output=True, text=True
)
if result.returncode != 0:
    print('pip stderr:', result.stderr[-300:])
import torch, torchvision
print(f'torch={torch.__version__}  cuda={torch.cuda.is_available()}')
print('OK')

# CELL 2: Clone One-D-Piece repo + download weights
import subprocess, os, sys

REPO_DIR = '/content/One-D-Piece'
if not os.path.isdir(REPO_DIR):
    print('Cloning turingmotors/One-D-Piece...')
    r = subprocess.run(
        ['git', 'clone', '--depth', '1',
         'https://github.com/turingmotors/One-D-Piece.git', REPO_DIR],
        capture_output=True, text=True
    )
    print(r.stdout or 'cloned')
    if r.returncode != 0: print('ERROR:', r.stderr)
else:
    print('Repo already present.')

sys.path.insert(0, REPO_DIR)

WEIGHT = '/content/pytorch_model.bin'
HF_URL = 'https://huggingface.co/turing-motors/One-D-Piece-L-256/resolve/main/pytorch_model.bin'

if os.path.isfile(WEIGHT) and os.path.getsize(WEIGHT) > 1e9:
    print(f'Weights already present ({os.path.getsize(WEIGHT)/1e9:.2f} GB)')
else:
    print('Downloading weights (~2.6 GB)...')
    r = subprocess.run(['wget', '-q', '--show-progress', '-O', WEIGHT, HF_URL])
    if not (r.returncode == 0 and os.path.isfile(WEIGHT)):
        print('wget failed, trying curl...')
        subprocess.run(['curl', '-L', '-o', WEIGHT, HF_URL])
    print(f'Downloaded: {os.path.getsize(WEIGHT)/1e9:.2f} GB')
print('Done.')

# CELL 3: Load the model
import sys, os, torch
import numpy as np

sys.path.insert(0, '/content/One-D-Piece')
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {DEVICE} | GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "none"}')

from omegaconf import OmegaConf
from modeling.titok import TiTok

cfg = OmegaConf.create({
    'model': {
        'vq_model': {
            'codebook_size':      4096,
            'token_size':         12,
            'use_l2_norm':        True,
            'commitment_cost':    0.25,
            'num_latent_tokens':  256,
            'vit_enc_model_size': 'large',
            'vit_dec_model_size': 'large',
            'vit_enc_patch_size': 16,
            'vit_dec_patch_size': 16,
            'finetune_decoder':   True,
        }
    },
    'dataset': {'preprocessing': {'crop_size': 256}}
})

print('Instantiating TiTok-L-256...')
model = TiTok(cfg)

print('Loading checkpoint...')
ckpt = torch.load('/content/pytorch_model.bin', map_location='cpu', weights_only=False)
if isinstance(ckpt, dict) and any(k in ckpt for k in ('state_dict', 'model')):
    state = ckpt.get('state_dict', ckpt.get('model'))
else:
    state = ckpt

keys = list(state.keys())
print(f'{len(keys)} keys. First 3: {keys[:3]}')
for prefix in ['model.', 'module.', 'vq_model.']:
    if sum(1 for k in keys[:10] if k.startswith(prefix)) >= 5:
        state = {k[len(prefix):]: v for k, v in state.items()}
        print(f'Stripped prefix: "{prefix}"')
        break

missing, unexpected = model.load_state_dict(state, strict=False)
print(f'Missing: {len(missing)}  Unexpected: {len(unexpected)}')
model = model.to(DEVICE).eval()
print(f'Model ready — {sum(p.numel() for p in model.parameters())/1e6:.0f}M params')

# CELL 4: Tokenizer interface + smoke test
import torch, numpy as np
from PIL import Image
import torchvision.transforms as T
from skimage.metrics import structural_similarity as ssim_fn
from skimage.metrics import peak_signal_noise_ratio as psnr_fn

# One-D-Piece expects [0,1] input — NO normalization
TO_TENSOR = T.Compose([
    T.Resize(256, interpolation=T.InterpolationMode.LANCZOS),
    T.CenterCrop(256),
    T.ToTensor(),
])

def pil_to_tensor(pil):
    if pil.mode != 'RGB': pil = pil.convert('RGB')
    return TO_TENSOR(pil).unsqueeze(0).to(DEVICE)

def tensor_to_pil(t):
    arr = t.squeeze(0).permute(1,2,0).cpu().float().numpy()
    return Image.fromarray((np.clip(arr, 0, 1) * 255).astype(np.uint8))

@torch.no_grad()
def tokenize(pil_img):
    """PIL -> numpy int64 array shape (256,)"""
    x = pil_to_tensor(pil_img)
    _, info = model.encode(x)
    return info['min_encoding_indices'].squeeze().cpu().numpy().astype(np.int64)

@torch.no_grad()
def reconstruct(token_ids, k):
    """First k tokens -> PIL image. Positions k+1..256 set to 0."""
    k = max(1, min(int(k), 256))
    padded = np.zeros(256, dtype=np.int64)
    padded[:k] = token_ids[:k]
    codes = torch.tensor(padded).reshape(1, 1, 256).to(DEVICE)
    rec = model.decode_tokens(codes)
    return tensor_to_pil(rec)

def measure_qoe(orig_pil, rec_pil):
    o = np.array(orig_pil.convert('RGB').resize((256,256), Image.LANCZOS))
    r = np.array(rec_pil.convert('RGB').resize((256,256), Image.LANCZOS))
    psnr_val = float(psnr_fn(o, r, data_range=255))
    ssim_val = float(ssim_fn(o, r, channel_axis=2, data_range=255))
    return {'psnr': psnr_val, 'ssim': ssim_val, 'qoe': psnr_val}

# Smoke test
print('Smoke test...')
from skimage import data as skdata
tpil = Image.fromarray(skdata.astronaut())
toks = tokenize(tpil)
print(f'  tokens: {toks.shape}  range=[{toks.min()},{toks.max()}]')
assert toks.shape == (256,) and toks.max() < 4096
m16  = measure_qoe(tpil, reconstruct(toks, 16))
m128 = measure_qoe(tpil, reconstruct(toks, 128))
m256 = measure_qoe(tpil, reconstruct(toks, 256))
print(f'  k=16:  PSNR={m16["psnr"]:.1f}dB  SSIM={m16["ssim"]:.3f}')
print(f'  k=128: PSNR={m128["psnr"]:.1f}dB  SSIM={m128["ssim"]:.3f}')
print(f'  k=256: PSNR={m256["psnr"]:.1f}dB  SSIM={m256["ssim"]:.3f}')
assert m16['psnr'] <= m128['psnr'] + 0.5 and m128['psnr'] <= m256['psnr'] + 0.5, 'Not monotone!'
print('Smoke test passed.')

# CELL 5: Load test images
# Primary: Tiny-ImageNet (in-distribution with One-D-Piece's ImageNet training)
# Fallback: skimage built-ins
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def arr2pil(a):
    if a.ndim == 2: a = np.stack([a,a,a], axis=-1)
    if a.dtype != np.uint8: a = (a*255).clip(0,255).astype(np.uint8)
    return Image.fromarray(a).convert('RGB')

test_images = []

# Try Tiny-ImageNet first (same domain as One-D-Piece training)
try:
    from datasets import load_dataset
    print('Loading Tiny-ImageNet validation images (in-distribution)...')
    ds = load_dataset('zh-plus/tiny-imagenet', split='valid', streaming=True,
                      trust_remote_code=True)
    # Sample diverse classes
    for i, sample in enumerate(ds):
        if len(test_images) >= 8: break
        img = sample['image'].convert('RGB').resize((256, 256), Image.LANCZOS)
        test_images.append((f'tinyimagenet_{i}', img))
    print(f'Loaded {len(test_images)} Tiny-ImageNet images')
except Exception as e:
    print(f'Tiny-ImageNet unavailable ({e}), using skimage fallback')

# Fallback to skimage
if len(test_images) < 4:
    from skimage import data as skdata
    test_images = [
        ('astronaut', arr2pil(skdata.astronaut())),
        ('chelsea',   arr2pil(skdata.chelsea())),
        ('coffee',    arr2pil(skdata.coffee())),
        ('camera',    arr2pil(skdata.camera())),
        ('coins',     arr2pil(skdata.coins())),
    ]
    print(f'Using {len(test_images)} skimage images')

print(f'Images: {[n for n,_ in test_images]}')

fig, axes = plt.subplots(1, len(test_images),
                          figsize=(3*len(test_images), 3), facecolor='#0d0f1a')
if len(test_images) == 1: axes = [axes]
for ax, (name, img) in zip(axes, test_images):
    ax.imshow(img.resize((128,128), Image.LANCZOS))
    ax.set_title(name[:14], color='white', fontsize=8)
    ax.axis('off')
plt.tight_layout(); plt.show()
print('Images ready.')

# CELL 6: Pre-compute QoE(k) lookup tables  (~8 min on T4)
import numpy as np

K_VALS  = [1, 4, 8, 12, 16, 24, 32, 48, 64, 80, 96, 112, 128, 144, 160, 192, 224, 256]
K_DENSE = list(range(16, 257, 16))  # 16,32,...,256  for MAC sim
K_ALL   = sorted(set(K_VALS + K_DENSE))

exp1_results = {}
all_luts     = {}

for img_name, pil_img in test_images:
    print(f'\n{img_name}:')
    toks = tokenize(pil_img)
    lut  = {}
    for k in K_ALL:
        m      = measure_qoe(pil_img, reconstruct(toks, k))
        lut[k] = m['psnr']       # PSNR as QoE metric
    lut[0] = lut[min(K_ALL)] * 0.75   # MLLM generative floor at k=0
    psnrs  = [lut[k] for k in K_VALS]
    mono   = all(psnrs[i] <= psnrs[i+1] + 0.3 for i in range(len(psnrs)-1))
    v      = [lut[k] for k in [16, 64, 128, 256]]
    print(f'  PSNR k=16:{v[0]:.1f}  k=64:{v[1]:.1f}  k=128:{v[2]:.1f}  k=256:{v[3]:.1f}dB  '
          f'monotone:{"YES" if mono else "NO"}')
    exp1_results[img_name] = {'k': K_VALS, 'psnr': psnrs, 'toks': toks, 'pil': pil_img}
    all_luts[img_name]     = lut

PRIMARY = test_images[0][0]
print(f'\nExp1 complete. Primary image for MAC simulation: {PRIMARY}')

# CELL 7: Channel model + Layered TXOP MAC simulation
#
# ── Physical rationale ────────────────────────────────────────────────────────
# Wi-Fi 6 MCS7: 86 Mbit/s raw rate.
# 256 tokens × 12 bits = 3,072 bits → 0.036ms transmission time (negligible).
# The deadline pressure comes entirely from RETRANSMISSION RTT:
#   RTT = 8ms (realistic congested Wi-Fi: SIFS + ACK + DIFS + random backoff + queuing)
# Under poor burst channel: 4-5 retransmission rounds needed.
# 4 rounds × 8ms = 32ms → fits inside 33.3ms by 1ms margin (risky)
# 5 rounds × 8ms = 40ms → EXCEEDS 33.3ms deadline → frame dropped → FREEZE
#
# TCLA Layered TXOP:
#   PPDU1 (base):   32 tokens at MCS_low → 0ms tx + 8ms RTT = 8ms  (guaranteed)
#   PPDU2 (enh):  k_enh tokens at MCS_high → 0ms tx + 8ms RTT = 8ms  (opportunistic)
#   Total: 16ms ≤ 33.3ms → ALWAYS meets deadline, zero retransmissions
#
# Conventional:
#   1 PPDU: 256 tokens at MCS_high → 0ms tx + retransmit until done or deadline
#   Under poor channel: needs 5+ rounds → 40ms+ → DEADLINE MISS → FREEZE
# ─────────────────────────────────────────────────────────────────────────────

import numpy as np, random
random.seed(42); np.random.seed(42)

# ── Gilbert-Elliott burst-loss channel ───────────────────────────────────────
# Longer burst lengths than default — realistic for busy shared Wi-Fi
# p_bg = transition bad→good = 1/avg_burst_length
# poor: avg burst = 1/0.08 ≈ 12 MPDUs → very damaging to a 16-MPDU frame
class GEChannel:
    CONFIGS = {
        'excellent': dict(p_g=0.01, p_b=0.30, p_gb=0.02, p_bg=0.60, per=0.02),
        'good':      dict(p_g=0.02, p_b=0.55, p_gb=0.05, p_bg=0.25, per=0.13),
        'moderate':  dict(p_g=0.03, p_b=0.75, p_gb=0.08, p_bg=0.12, per=0.31),
        'poor':      dict(p_g=0.05, p_b=0.88, p_gb=0.10, p_bg=0.08, per=0.56),
    }
    def __init__(self, s='good'): self.set(s)
    def set(self, s):
        self.__dict__.update(self.CONFIGS[s])
        self.severity = s; self.state = 'GOOD'
    def tx(self, n):
        rx = np.zeros(n, dtype=bool)
        for i in range(n):
            if self.state == 'GOOD':
                if random.random() < self.p_gb: self.state = 'BAD'
                rx[i] = random.random() > self.p_g
            else:
                if random.random() < self.p_bg: self.state = 'GOOD'
                rx[i] = random.random() > self.p_b
        return rx

# ── MAC parameters ────────────────────────────────────────────────────────────
RTT    = 8.0      # ms — retransmission round trip (congested Wi-Fi)
TMAX   = 33.3     # ms — 30fps hard deadline
KTOT   = 256      # total tokens per frame
K_BASE = 32       # base layer — fixed, always sent, guaranteed delivery
TPM    = 16       # tokens per MPDU

# MCS-specific erasure probs:
#   MCS_low  (base):  heavy coding → very low erasure even in bad state
#   MCS_high (enh):   standard coding → channel erasure applies normally
BASE_PG, BASE_PB = 0.005, 0.04   # MCS_low: ~0% effective PER
ENH_PG,  ENH_PB  = 0.02,  0.50   # MCS_high: standard channel PER

# Enhancement budget: TMAX minus base PPDU (RTT only, tx≈0) minus enh RTT
K_ENH_MAX = KTOT - K_BASE   # 224 tokens — all remaining tokens
# Both PPDUs fit: 8ms (base RTT) + 8ms (enh RTT) = 16ms << 33.3ms

def nqoe(lut, k):
    return lut[min(lut.keys(), key=lambda x: abs(x - k))]

def make_ge(severity, p_g, p_b):
    """GE channel: state transitions from severity config, erasure from MCS."""
    cfg = GEChannel.CONFIGS[severity]
    ch  = GEChannel.__new__(GEChannel)
    ch.p_g, ch.p_b   = p_g, p_b
    ch.p_gb, ch.p_bg = cfg['p_gb'], cfg['p_bg']
    ch.state, ch.severity, ch.per = 'GOOD', severity, cfg['per']
    return ch

def n_mpdus(k): return int(np.ceil(k / TPM))

def sim_tcla_layered(severity, lut, k_enh):
    """
    Layered TXOP TCLA — no retransmission, hard latency guarantee.

    PPDU1 (base layer):
      k_base tokens at MCS_low → near-zero erasure → always delivered
      Guarantees QoE(k_base) > 0 → no freeze possible
      Cost: 1 RTT = 8ms

    PPDU2 (enhancement layer):
      k_enh tokens at MCS_high → standard channel erasure
      k_enh is VARIABLE — adapted each frame via Block ACK (no MLLM)
      Cost: 1 RTT = 8ms

    Total latency: 16ms — always under TMAX=33.3ms.
    Block ACK outcome → k_rx → QoE(k_rx) from lookup → adapt k_enh next frame.
    """
    k_enh = max(0, min(int(k_enh), K_ENH_MAX))

    # PPDU 1: base layer at MCS_low
    ch_base   = make_ge(severity, BASE_PG, BASE_PB)
    rx_base   = ch_base.tx(n_mpdus(K_BASE))
    k_base_rx = int(np.sum(rx_base) * TPM)
    lat       = RTT   # base layer RTT

    # PPDU 2: enhancement layer at MCS_high
    k_enh_rx = 0
    if k_enh > 0:
        ch_enh   = make_ge(severity, ENH_PG, ENH_PB)
        rx_enh   = ch_enh.tx(n_mpdus(k_enh))
        k_enh_rx = int(np.sum(rx_enh) * TPM)
        lat     += RTT   # enhancement layer RTT

    k_rx   = min(k_base_rx + k_enh_rx, KTOT)
    freeze = (k_base_rx == 0)   # base layer fully lost — extremely rare at MCS_low
    qoe    = lut[0] if freeze else nqoe(lut, k_rx)

    return dict(
        k_base_rx=k_base_rx, k_enh_rx=k_enh_rx, k_rx=k_rx,
        lat=lat, qoe=qoe, freeze=freeze
    )

def sim_conv(severity, lut, max_retx=8):
    """
    Conventional: needs ALL 256 tokens to decode frame (H.265 equivalent).
    Retransmits until all recovered OR budget exhausted.
    Any remaining loss after budget = frame freeze = QoE 0.
    (TCLA avoids this by accepting partial delivery + MLLM reconstruction)
    """
    ch      = make_ge(severity, ENH_PG, ENH_PB)
    n       = n_mpdus(KTOT)
    rx      = np.zeros(n, dtype=bool)
    elapsed = 0.0

    # Initial transmission
    rx     |= ch.tx(n)
    elapsed += RTT

    # Retransmit until all recovered or no time left for another round
    for _ in range(max_retx):
        lost = np.where(~rx)[0]
        if len(lost) == 0: break              # all recovered — success
        if elapsed + RTT > TMAX: break        # next round exceeds deadline — give up
        rx[lost] |= ch.tx(len(lost))
        elapsed  += RTT

    remaining = int(np.sum(~rx))

    # Conventional codec: any remaining loss = cannot decode = freeze
    # TCLA does not have this problem — MLLM reconstructs missing tokens
    miss = remaining > 0
    return dict(
        k_rx  = KTOT if not miss else int(np.sum(rx) * TPM),
        lat   = elapsed,
        qoe   = 0.0 if miss else nqoe(lut, KTOT),   # all-or-nothing: full or freeze
        miss  = miss,
        freeze= miss,
    )

# Sanity check: show expected retransmission rounds per channel
print('MAC model parameters:')
print(f'  RTT={RTT}ms  TMAX={TMAX}ms  max_rounds={int(TMAX/RTT)}')
print(f'  Base layer: k={K_BASE} tokens, MCS_low (p_bad={BASE_PB}), cost=1×RTT={RTT}ms')
print(f'  Enh layer:  k=0..{K_ENH_MAX} tokens, MCS_high (p_bad={ENH_PB}), cost=1×RTT={RTT}ms')
print(f'  TCLA total: 2×RTT={2*RTT}ms — always fits')
print(f'  Conv budget: {int(TMAX/RTT)} retransmission rounds max')
print()
print('Expected behavior:')
for sev in ['excellent','good','moderate','poor']:
    cfg = GEChannel.CONFIGS[sev]
    avg_burst = 1.0 / cfg['p_bg']
    # Expected first-pass losses for 16 MPDUs
    pi_bad = cfg['p_gb'] / (cfg['p_gb'] + cfg['p_bg'])
    mean_per = pi_bad * cfg['p_b'] + (1-pi_bad) * cfg['p_g']
    expected_lost = n_mpdus(KTOT) * mean_per
    print(f'  {sev:<10}: mean_PER={mean_per*100:.0f}%  avg_burst={avg_burst:.1f}MPDUs  '
          f'expected_lost={expected_lost:.1f}/{n_mpdus(KTOT)} MPDUs')
print('\nMAC model ready.')

# CELL 8: Experiment 2 — Layered TXOP TCLA vs Conventional
#
# Adaptation loop:
#   After each frame, Block ACK reveals k_rx → nqoe(lut, k_rx) = predicted QoE
#   No MLLM inference. Token position IS the quality signal.
#   k_enh increases when QoE >= target (channel good → probe for more quality)
#   k_enh decreases when QoE <  target (channel bad  → conserve budget)
import numpy as np

N       = 500
PRIMARY = test_images[0][0]
lut     = all_luts[PRIMARY]

# QoE target: PSNR at k≈80 tokens (midrange quality, reliably achievable)
QT      = nqoe(lut, 80)    # dB — adapts to actual model quality on loaded images
DU      = 32               # k_enh step up — increase moderately
DD      = 16               # k_enh step down — decrease conservatively
                           # asymmetric: probe quality aggressively, retreat slowly

exp2 = {}
print(f'{N} trials per channel condition')
print(f'Architecture: base k={K_BASE} (MCS_low, guaranteed) + '
      f'enh k_enh=0..{K_ENH_MAX} (MCS_high, adaptive)')
print(f'QoE target: {QT:.1f} dB PSNR (k≈80 tokens)\n')

for sev in ['excellent', 'good', 'moderate', 'poor']:
    tq, cq, tl, cl, tf, cf, kenh_hist = [], [], [], [], [], [], []
    k_enh = K_ENH_MAX   # start optimistic — full enhancement

    for _ in range(N):
        rt = sim_tcla_layered(sev, lut, k_enh)
        rc = sim_conv(sev, lut)

        tq.append(rt['qoe']);    cq.append(rc['qoe'])
        tl.append(rt['lat']);    cl.append(rc['lat'])
        tf.append(rt['freeze']); cf.append(rc['freeze'])
        kenh_hist.append(k_enh)

        # Block ACK → k_rx → QoE → adapt k_enh (zero MLLM)
        if rt['qoe'] >= QT:
            k_enh = min(k_enh + DU, K_ENH_MAX)
        else:
            k_enh = max(k_enh - DD, 0)

    exp2[sev] = dict(
        label=sev.capitalize(), per=GEChannel.CONFIGS[sev]['per'],
        tq=np.array(tq), cq=np.array(cq),
        tl=np.array(tl), cl=np.array(cl),
        freeze_tcla=np.mean(tf), freeze_conv=np.mean(cf),
        k_enh_mean=np.mean(kenh_hist),
    )
    tm, cm = np.mean(tq), np.mean(cq)
    print(f'{sev:<10}: '
          f'TCLA {tm:.1f}dB  Conv {cm:.1f}dB  Gain {tm-cm:+.1f}dB  '
          f'Freeze TCLA={np.mean(tf)*100:.1f}%  Conv={np.mean(cf)*100:.1f}%  '
          f'k_enh_avg={np.mean(kenh_hist):.0f}/{K_ENH_MAX}  '
          f'LatTCLA={np.mean(tl):.1f}ms  LatConv={np.mean(cl):.1f}ms')

print('\nExp2 complete.')
print('\nKey insight: Conv freeze rate grows with channel severity.')
print('When Conv freezes, QoE=0. TCLA never freezes — graceful degradation.')
print('Mean Conv QoE = (1-freeze_rate)×full_QoE + freeze_rate×0 → collapses fast.')

# CELL 9: Experiment 3 — Block ACK closed-loop adaptation over 120-frame video
#
# Demonstrates Claim 3: Block ACK gives QoE signal without MLLM.
# Predicted QoE:  PSNR from lut lookup using k_rx from Block ACK (real system)
# Actual QoE:     SSIM from reconstruction  (ground truth, not in real system)
# PSNR and SSIM are correlated but not identical → r < 1.0 (meaningful correlation)
import numpy as np

NF     = 120
QT3    = nqoe(lut, 80)    # same target as Exp2
DU3    = 32
DD3    = 16

# Channel phases: starts excellent, degrades, recovers
phase_seq = (['excellent']*25 + ['good']*20 + ['moderate']*20 +
             ['poor']*20 + ['good']*35)[:NF]

ptoks  = exp1_results[PRIMARY]['toks']
ppil   = exp1_results[PRIMARY]['pil']
frames = []
k_enh  = K_ENH_MAX   # start optimistic

print('Simulating 120-frame video with closed-loop k_enh adaptation...')
for idx, phase in enumerate(phase_seq):
    r = sim_tcla_layered(phase, lut, k_enh)

    # Predicted QoE from Block ACK: token position → PSNR lookup (no MLLM)
    qoe_pred = r['qoe']

    # Actual QoE: reconstruct and measure SSIM (ground truth, different metric)
    rec_pil    = reconstruct(ptoks, max(1, r['k_rx']))
    actual_qoe = measure_qoe(ppil, rec_pil)['ssim']   # SSIM ≠ PSNR → r < 1.0

    frames.append(dict(
        frame      = idx,
        phase      = phase,
        k_enh      = k_enh,
        k_base_rx  = r['k_base_rx'],
        k_enh_rx   = r['k_enh_rx'],
        k_rx       = r['k_rx'],
        qoe_pred   = qoe_pred,    # PSNR (dB) from Block ACK — zero MLLM
        qoe_actual = actual_qoe,  # SSIM ground truth
        lat        = r['lat'],
        freeze     = r['freeze'],
    ))

    # Adapt k_enh using ONLY Block ACK feedback — no MLLM needed
    if r['qoe'] >= QT3:
        k_enh = min(k_enh + DU3, K_ENH_MAX)
    else:
        k_enh = max(k_enh - DD3, 0)

# Correlation between Block ACK PSNR prediction and actual SSIM
# Normalise both to [0,1] so different scales don't affect correlation
pred  = np.array([f['qoe_pred']   for f in frames])
act   = np.array([f['qoe_actual'] for f in frames])
pn    = (pred - pred.min()) / (pred.max() - pred.min() + 1e-8)
an    = (act  - act.min())  / (act.max()  - act.min()  + 1e-8)
corr  = float(np.corrcoef(pn, an)[0, 1])
mae   = float(np.mean(np.abs(pn - an)))

exp3 = dict(frames=frames, corr=corr, mae=mae, qoe_target=QT3)

print(f'\nBlock ACK (PSNR) vs actual (SSIM) correlation: r={corr:.4f}  MAE={mae:.4f}')
print(f'Freeze events: {sum(f["freeze"] for f in frames)}/{NF}')
print('Token position in Block ACK predicts quality — zero MLLM inference needed.')

print('\nMean k_enh per channel phase:')
for ph in ['excellent', 'good', 'moderate', 'poor']:
    vals = [f['k_enh'] for f in frames if f['phase'] == ph]
    if vals:
        print(f'  {ph:<12}: k_enh_avg={np.mean(vals):.0f}/{K_ENH_MAX}  '
              f'PSNR_avg={np.mean([f["qoe_pred"] for f in frames if f["phase"]==ph]):.1f}dB')

print('\nExp3 complete.')

# CELL 10: Publication-quality figure
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
from PIL import Image

BG='#0d0f1a'; PAN='#13162a'; TC='#4FC3F7'; CV='#EF5350'
GN='#66BB6A'; OR='#FFA726'; PR='#CE93D8'; GR='#aaaacc'; WH='#e8e8f0'
PBG={'excellent':'#0a1a0a','good':'#0a0f1a','moderate':'#1a1a0a','poor':'#1a0a0a'}

def stl(ax, t=''):
    ax.set_facecolor(PAN); ax.tick_params(colors=GR, labelsize=8)
    for s in ['bottom','left']: ax.spines[s].set_color('#334')
    for s in ['top','right']:   ax.spines[s].set_visible(False)
    ax.grid(True, color='#1e2235', lw=0.6)
    ax.xaxis.label.set_color(GR); ax.yaxis.label.set_color(GR)
    if t: ax.set_title(t, color=WH, fontsize=8.5, fontweight='bold', pad=5)

def shade(ax, phases, ymax):
    prev, start = phases[0], 0
    for i, p in enumerate(phases + [None]):
        if p != prev:
            ax.axvspan(start, i, alpha=0.28, color=PBG.get(prev,'#111'), lw=0)
            if i - start > 4:
                ax.text((start+i)//2, ymax*0.91, prev.capitalize(),
                        ha='center', color=WH, fontsize=6)
            prev, start = p, i

fig = plt.figure(figsize=(22, 16), facecolor=BG)
gs  = gridspec.GridSpec(3, 4, figure=fig, hspace=0.50, wspace=0.38,
                        left=0.055, right=0.975, top=0.92, bottom=0.055)

fig.text(0.5, 0.960,
    'TCLA — Layered TXOP QoE-Driven Adaptation: Simulation Results',
    ha='center', color=WH, fontsize=14, fontweight='bold')
fig.text(0.5, 0.938,
    f'One-D-Piece-L-256 (real TTD tokenizer)  |  GE burst-loss Wi-Fi  |  '
    f'30fps TMAX={TMAX}ms  |  RTT={RTT}ms/round  |  Base={K_BASE}tok MCS_low + Enh adaptive',
    ha='center', color=GR, fontsize=8)

# ── Row 1L: QoE(k) curves ────────────────────────────────────────────
ax = fig.add_subplot(gs[0, 0:2])
stl(ax, 'Claim 1 — QoE(k) Monotone (One-D-Piece TTD Tokenizer)\n'
        'Each additional token improves reconstruction quality')
cm = plt.colormaps['tab10']
for i, (name, d) in enumerate(exp1_results.items()):
    ax.plot(d['k'], d['psnr'], color=cm(i), lw=1.8, label=name, alpha=0.9)
ymin, ymax = ax.get_ylim()
ax.axvline(K_BASE, color=OR, lw=1.5, ls='--', alpha=0.8,
           label=f'k_base={K_BASE} (base layer guarantee)')
ax.set_xlabel('Token count k'); ax.set_ylabel('PSNR (dB)')
ax.set_xlim(0, 256)
ax.legend(fontsize=7, loc='lower right', facecolor=BG, edgecolor='#334', labelcolor=WH)

# ── Row 1R: reconstruction strip ─────────────────────────────────────
ax_v = fig.add_subplot(gs[0, 2:4])
stl(ax_v, 'Progressive Reconstruction — Real One-D-Piece\n'
          'Base layer (k=32, orange) guarantees no freeze; enhancement adds quality')
ax_v.axis('off')
k_show = [4, 16, 32, 64, 128, 192, 256]
pos    = ax_v.get_position(); nk = len(k_show)
ptoks_show = exp1_results[PRIMARY]['toks']
ppil_show  = exp1_results[PRIMARY]['pil']
for idx, k in enumerate(k_show):
    rec = reconstruct(ptoks_show, k)
    q   = nqoe(all_luts[PRIMARY], k)
    sub = fig.add_axes([pos.x0 + idx/nk*pos.width + 0.002,
                        pos.y0 + 0.04, pos.width/nk - 0.006, pos.height*0.75])
    sub.imshow(np.array(rec.resize((128,128), Image.LANCZOS)))
    sub.axis('off')
    col = OR if k == K_BASE else WH
    for sp in sub.spines.values():
        sp.set_edgecolor(col); sp.set_linewidth(2.0 if k == K_BASE else 0)
    sub.set_title(f'k={k}\n{q:.1f}dB', color=col, fontsize=6.5, pad=2)

# ── Row 2L: QoE comparison bar chart ─────────────────────────────────
ax = fig.add_subplot(gs[1, 0:2])
stl(ax, f'Claim 2 — Mean QoE: TCLA vs Conventional ({N} trials)\n'
        f'Conv QoE = (1−freeze)×full_QoE + freeze×0  →  collapses under poor channel')
sevs  = list(exp2.keys())
xlabs = [f"{exp2[s]['label']}\n(PER≈{int(exp2[s]['per']*100)}%)" for s in sevs]
x = np.arange(len(sevs)); w = 0.35
tm  = [exp2[s]['tq'].mean() for s in sevs]
cm2 = [exp2[s]['cq'].mean() for s in sevs]
ts  = [exp2[s]['tq'].std()  for s in sevs]
cs  = [exp2[s]['cq'].std()  for s in sevs]
ekw = dict(ecolor=WH, capsize=4, linewidth=1.2)
ax.bar(x-w/2, tm,  w, yerr=ts, color=TC, alpha=0.85,
       label='TCLA (layered, no retransmit)', error_kw=ekw)
ax.bar(x+w/2, cm2, w, yerr=cs, color=CV, alpha=0.85,
       label='Conventional (retransmit→freeze)', error_kw=ekw)
for i, (a, b) in enumerate(zip(tm, cm2)):
    g = a - b; c = GN if g > 0 else CV
    ax.text(i, max(a,b)+0.3, f'{g:+.1f}', ha='center', fontsize=8,
            color=c, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(xlabs, fontsize=7.5)
ax.set_ylabel('Mean PSNR (dB)')
ax.legend(facecolor=BG, edgecolor='#334', labelcolor=WH, fontsize=8)

# ── Row 2R: Freeze rate ───────────────────────────────────────────────
ax = fig.add_subplot(gs[1, 2:4])
stl(ax, 'Claim 2 — Freeze Rate: TCLA Never Freezes vs Conventional\n'
        f'Conv freeze = deadline miss after {int(TMAX/RTT)} retransmission rounds × {RTT}ms RTT')
fr_t = [exp2[s]['freeze_tcla']*100 for s in sevs]
fr_c = [exp2[s]['freeze_conv']*100 for s in sevs]
ax.bar(x-w/2, fr_t, w, color=TC, alpha=0.85, label='TCLA freeze %')
ax.bar(x+w/2, fr_c, w, color=CV, alpha=0.85, label='Conv freeze %')
for i, (a, b) in enumerate(zip(fr_t, fr_c)):
    if b > 0.5:
        ax.text(i+w/2, b+0.5, f'{b:.0f}%', ha='center',
                fontsize=8, color=CV, fontweight='bold')
    ax.text(i-w/2, max(a,0.5)+0.5, f'{a:.1f}%', ha='center',
            fontsize=7, color=GN if a < 1 else CV)
ax.set_xticks(x); ax.set_xticklabels(xlabs, fontsize=7.5)
ax.set_ylabel('Freeze rate (%)')
ax.set_ylim(bottom=0)
ax.legend(facecolor=BG, edgecolor='#334', labelcolor=WH, fontsize=8)

# ── Row 3L: k_enh adaptation trace ───────────────────────────────────
ax = fig.add_subplot(gs[2, 0:2])
stl(ax, 'Claim 3 — Block ACK Drives k_enh Adaptation (Zero MLLM)\n'
        'Enhancement tokens increase when channel is good, decrease when bad')
frames  = exp3['frames']
fi      = [f['frame']    for f in frames]
k_enhs  = [f['k_enh']   for f in frames]
k_rxs   = [f['k_rx']    for f in frames]
phases  = [f['phase']   for f in frames]
ax.set_ylim(0, K_ENH_MAX * 1.12)
shade(ax, phases, K_ENH_MAX)
ax.fill_between(fi, k_enhs, alpha=0.15, color=TC)
ax.plot(fi, k_enhs, color=TC,       lw=1.8, label=f'k_enh sent (max={K_ENH_MAX})')
ax.plot(fi, [f['k_enh_rx'] for f in frames],
        color='#B3E5FC', lw=1.0, alpha=0.7, label='k_enh received (Block ACK)')
ax.axhline(0,         color=CV, lw=0.8, ls=':', alpha=0.4)
ax.axhline(K_ENH_MAX, color=GN, lw=0.8, ls=':', alpha=0.4)
ax.set_xlabel('Video frame index')
ax.set_ylabel('Enhancement token count')
ax.set_xlim(0, len(fi)-1)
ax.legend(fontsize=7.5, facecolor=BG, edgecolor='#334', labelcolor=WH)

# ── Row 3R: Block ACK prediction accuracy ────────────────────────────
ax = fig.add_subplot(gs[2, 2:4])
stl(ax, f"Claim 3 — Block ACK (PSNR) Predicts Actual Quality (SSIM)\n"
        f"r={exp3['corr']:.4f}   MAE={exp3['mae']:.4f}   "
        f"→ k_enh adapted with zero MLLM inference")
pred_raw = np.array([f['qoe_pred']   for f in frames])
act_raw  = np.array([f['qoe_actual'] for f in frames])
# Normalise for plotting on same axis
pn = (pred_raw - pred_raw.min()) / (pred_raw.max() - pred_raw.min() + 1e-8)
an = (act_raw  - act_raw.min())  / (act_raw.max()  - act_raw.min()  + 1e-8)
ax.set_ylim(0, 1.1)
shade(ax, phases, 1.0)
ax.plot(fi, an, color=GN,  lw=1.8, label='Actual SSIM (normalised, ground truth)')
ax.plot(fi, pn, color=TC,  lw=1.6, ls='--', label='Block ACK PSNR (normalised)')
ax.fill_between(fi, an, pn, alpha=0.15, color=PR, label='Prediction error')
ax.set_xlabel('Video frame index')
ax.set_ylabel('Normalised QoE')
ax.set_xlim(0, len(fi)-1)
ax.legend(fontsize=7.5, facecolor=BG, edgecolor='#334', labelcolor=WH)

plt.savefig('/content/tcla_results.png', dpi=150, bbox_inches='tight', facecolor=BG)
plt.show()
print('Figure saved.')

# CELL 11: Summary table + download
import numpy as np

print('='*76)
print('TCLA LAYERED TXOP — One-D-Piece-L-256 Real TTD Tokenizer')
print('='*76)

print(f'\nChannel model:')
print(f'  RTT = {RTT}ms per retransmission round  (congested Wi-Fi: SIFS+ACK+DIFS+backoff)')
print(f'  TMAX = {TMAX}ms  →  max {int(TMAX/RTT)} retransmission rounds for conventional')
print(f'  TCLA uses 2 RTTs (base + enh) = {2*RTT}ms — always under deadline')

print(f'\nQoE(k) — mean PSNR across images:')
kr  = [16, 32, 64, 128, 192, 256]
avg = {k: np.mean([all_luts[n].get(k, nqoe(all_luts[n],k))
                   for n in all_luts]) for k in kr}
print('  k:    ' + ''.join(f'{k:>8}' for k in kr))
print('  PSNR: ' + ''.join(f'{avg[k]:>7.1f}dB' for k in kr))

print(f'\nTCLA (Layered TXOP) vs Conventional ({N} trials):')
print(f'{"Channel":<12}{"TCLA":>9}{"Conv":>9}{"Gain":>8}'
      f'{"FreezeT":>10}{"FreezeC":>10}{"k_enh_avg":>12}')
print('-'*72)
for s, r in exp2.items():
    tm, cm = r['tq'].mean(), r['cq'].mean()
    print(f"{s:<12}{tm:>8.1f}dB{cm:>8.1f}dB{tm-cm:>+8.1f}dB"
          f"{r['freeze_tcla']*100:>9.1f}%"
          f"{r['freeze_conv']*100:>9.1f}%"
          f"{r['k_enh_mean']:>10.0f}/{K_ENH_MAX}")

print(f'\nBlock ACK Prediction (Exp 3):')
print(f'  PSNR(Block ACK) vs SSIM(actual):  r={exp3["corr"]:.4f}  MAE={exp3["mae"]:.4f}')
print(f'  Freeze events:  {sum(f["freeze"] for f in exp3["frames"])}/120')

print('\nThree patent claims demonstrated:')
print('  Claim 1: QoE(k) monotone — One-D-Piece TTD training produces '
      'ordered importance (proven on real images)')
print('  Claim 2: TCLA freeze rate ≈0%; Conv freeze rate grows with channel '
      'degradation → TCLA wins under moderate/poor')
print('  Claim 3: Block ACK token position correlates with actual quality '
      '→ k_enh adapted without any MLLM inference')

from google.colab import files
files.download('/content/tcla_results.png')
print('\nDownloaded.')